spring:
  application:
    name: watchlist-service
  datasource:
    url: jdbc:postgresql://${POSTGRES_HOST:localhost}:${POSTGRES_PORT:5432}/${POSTGRES_DB:stockflow}
    username: ${POSTGRES_USER:stockflow}
    password: ${POSTGRES_PASSWORD:StockFlow@2024}
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        default_schema: watchlist_schema
    show-sql: false
server:
  port: 8093
eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_CLIENT_SERVICEURL_DEFAULTZONE:http://localhost:8761/eureka}
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus
  tracing:
    sampling: { probability: 1.0 }
  zipkin:
    tracing:
      endpoint: ${MANAGEMENT_ZIPKIN_TRACING_ENDPOINT:http://localhost:9411/api/v2/spans}
springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true
logging:
  level:
    com.stockflow: DEBUG
